version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: PantryPalDB
    restart: always
    volumes:
      - ./init_PantryPal.sql:/docker-entrypoint-initdb.d/init.sql
      - pantrypal_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pantrypal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5434:5432"

volumes:
  pantrypal_data: